version: '3'

tasks:
  gp:
    description: git push with changes
    cmds:
      - git status
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push
      - git push remote origin https://gitlab.com/sakharamgit/cloudutsuk.git
      