version: '3'

tasks:
  gp:
    description: git push with changes
    cmds:
      - git status
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push
      - git push -u origin gitlab

# git remote add origin https://git@gitlab.com:sakharamgit/cloudutsuk.git
      