version: '3'

tasks:
  update:
    desc: Test and Push Changes
    cmds:
      - task: test-site
      - task: gp
  gp:
    desc: git push with changes
    # git remote add gitlab git@gitlab.com:sakharamgit/cloudutsuk.git
    # git remote add github git@github.com:SakharamS/sakharams.github.io.git
    cmds:
      - git status
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push github 
      - git push gitlab

  test-site:
    desc: test website
    cmds:
      - bundle exec htmlproofer _site/ --disable-external=true --ignore-urls "/^http://127.0.0.1/,/^http://0.0.0.0/,/^http://localhost/"
      