version: '3'

tasks:
  gp:
    description: git push with changes
    # git remote add gitlab git@gitlab.com:sakharamgit/cloudutsuk.git
    # git remote add github git@github.com:SakharamS/sakharams.github.io.git
    cmds:
      - git status
      - git add .
      - git commit -m "{{.CLI_ARGS}}"
      - git push github 
      - git push gitlab

      